- name: Pre-Install | Set default facts
  set_fact:
    use_firewalld: false
    configure_consul: false
    configure_carp: false

- name: Pre-Install | Check running services
  service_facts:

- name: Pre-Install | Check if CARP is to be configured
  when: bsd_iscsi_initiator.carp is defined
  set_fact:
    configure_carp: true

- name: Pre-Install | Check Consul configuration
  when:
  - bsd_iscsi_initiator_config_consul | lower == 'true'
  - not (ansible_facts.services | map('quote') | join(',') | regex_search('consul'))
  fail: msg="Consul service not found - Cannot configure it"

- name: Pre-Install | Check cluster configuration
  when:
  - bsd_iscsi_initiator_cluster_aware | lower == 'true'
  - not (ansible_facts.services | map('quote') | join(',') | regex_search('pacemaker'))
  fail: msg="Pacemaker service not found - Cannot configure it"

- name: Pre-Install | Get Consul facts
  when:
  - bsd_iscsi_initiator_config_consul | lower == 'true'
  - ansible_facts.services | map('quote') | join(',') | regex_search('consul')
  set_fact:
    configure_consul: true

- name: Pre-Install | Cluster-aware facts
  when: bsd_iscsi_initiator_cluster_aware | lower == 'true'
  block:
  - name: Pre-Install | Get crm node name
    command: crm_node -n
    changed_when: false
    register: crm_result

  - name: Pre-Install | Set cluster facts
    set_fact:
      crm_node_name: '{{ crm_result.stdout }}'
