---
# tasks file for ansible-bsd-iscsi-initiator

- name: Variables by OS
  include_vars: "{{ item }}"
  tags: always
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- import_tasks: bsd_iscsi_initiator_pre_install.yml
  tags:
    - bsd_iscsi_initiator-pre-install

- import_tasks: bsd_iscsi_initiator_install.yml
  tags:
    - bsd_iscsi_initiator-install

- import_tasks: bsd_iscsi_initiator_post_install.yml
  tags:
    - bsd_iscsi_initiator-post-install
